In [1]:
import pandas as pd
import numpy as np
import os
from progressbar import progressbar
from copy import deepcopy

In [2]:
# store all to be joined
join_all_list = []

In [3]:
join_all_list

[]

## Galactic folder

In [4]:
flist_galactic = os.listdir('../data/redo_data_Sep2026/galactic/')

In [5]:
data_gal_list = []

for fname in progressbar(flist_galactic):

    if '.csv' in fname:
        data_galactic_temp = pd.read_csv('../data/redo_data_Sep2026/galactic/' + fname, header=None,
                                        skiprows=1, names=['N','source_id','ra','dec','x','y','plx','pmra','pmdec','plxe','pmrae',
                                                          'pmdece','pmcorr','g_mag','bp_rp','Sigma','qflag','memberprob'], index_col=False)
        data_galactic_temp['source'] = 'galactic/' + fname
        data_gal_list.append(data_galactic_temp[data_galactic_temp['dec'] > -28])

data_gal = pd.concat(data_gal_list, ignore_index=True)

100% (169 of 169) |######################| Elapsed Time: 0:00:04 Time:  0:00:040000

In [6]:
data_gal.shape

(1000805, 19)

In [7]:
data_gal.keys()

Index(['N', 'source_id', 'ra', 'dec', 'x', 'y', 'plx', 'pmra', 'pmdec', 'plxe',
       'pmrae', 'pmdece', 'pmcorr', 'g_mag', 'bp_rp', 'Sigma', 'qflag',
       'memberprob', 'source'],
      dtype='object')

In [8]:
data_gal['full_id'] = [str(data_gal.iloc[i]['source']) + '/' + str(data_gal.iloc[i]['source_id']) for i in range(data_gal.shape[0])]

In [9]:
min(data_gal['ra']) >= 0 and max(data_gal['ra']) < 360

True

In [10]:
min(data_gal['dec']) > -90 and max(data_gal['dec']) < 90

True

In [11]:
data_gal_join = data_gal[['full_id', 'ra', 'dec']]

In [12]:
data_gal_join.drop_duplicates(subset=['ra', 'dec']).shape[0] == data_gal_join.shape[0]

True

In [13]:
data_gal_join.shape

(1000805, 3)

In [14]:
data_gal_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [15]:
data_gal_join

                                           full_id          ra        dec
0        galactic/NGC_6293.csv/4108888765614004480  257.470212 -26.634115
1        galactic/NGC_6293.csv/4108888769943030016  257.471862 -26.634367
2        galactic/NGC_6293.csv/4108888701277821824  257.472819 -26.634777
3        galactic/NGC_6293.csv/4108888769937920640  257.468382 -26.632580
4        galactic/NGC_6293.csv/4108888770006949248  257.467777 -26.631082
...                                            ...         ...        ...
1000800  galactic/NGC_6356.csv/4122898811505552896  261.011744 -17.743845
1000801  galactic/NGC_6356.csv/4122898884546588160  261.011275 -17.739763
1000802  galactic/NGC_6356.csv/4122898811522252544  261.012060 -17.740681
1000803  galactic/NGC_6356.csv/4122898884555330048  261.010804 -17.739155
1000804  galactic/NGC_6356.csv/4122898884546588032  261.011466 -17.739460

[1000805 rows x 3 columns]

In [16]:
join_all_list.append(data_gal_join)

In [17]:
len(join_all_list[0])

1000805

## Open clusters folder

In [18]:
data_opencluster = pd.read_csv('../data/redo_data_Sep2026/openclusters/members.csv')

In [19]:
data_opencluster.shape

(1291929, 63)

In [20]:
data_opencluster_use = deepcopy(data_opencluster[data_opencluster['dec'] > -28].drop_duplicates(subset=['ra','dec'], keep='first'))

In [21]:
data_opencluster_use.shape

(792844, 63)

In [22]:
data_opencluster.shape[0] - data_opencluster_use.shape[0]

499085

In [23]:
data_opencluster_use['source'] = 'openclusters/members/'

In [24]:
data_opencluster_use['full_id'] = [str(data_opencluster_use.iloc[i]['source']) + '/' + str(data_opencluster_use.iloc[i]['source_id']) 
                               for i in range(data_opencluster_use.shape[0])]

In [25]:
data_opencluster_join = data_opencluster_use[['full_id','ra','dec']]

In [26]:
data_opencluster_join.drop_duplicates(subset=['ra', 'dec']).shape[0] == data_opencluster_join.shape[0]

True

In [27]:
min(data_opencluster_join['ra']) >= 0 and max(data_opencluster_join['ra']) < 360

True

In [28]:
min(data_opencluster_join['dec']) > -90 and max(data_opencluster_join['dec']) < 90

True

In [29]:
data_opencluster_join.shape

(792844, 3)

In [30]:
data_opencluster_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [31]:
data_opencluster_join

                                           full_id          ra        dec
0        openclusters/members//1996314203783884544  345.384660  53.575661
1        openclusters/members//1997123787936918656  349.375671  55.888239
2        openclusters/members//1997227928003678848  350.228229  56.225701
3        openclusters/members//1998973608873873152  354.235696  58.135253
4        openclusters/members//2002532006459866240  342.869732  53.892829
...                                            ...         ...        ...
1291924  openclusters/members//2229376309127583616  333.563223  70.235228
1291925  openclusters/members//2229564527477739264  333.352279  70.251419
1291926  openclusters/members//2229568792380613120  333.171887  70.313901
1291927  openclusters/members//2229569720093542528  333.293173  70.410132
1291928  openclusters/members//2229580921368247680  333.148706  70.374695

[792844 rows x 3 columns]

In [32]:
join_all_list.append(data_opencluster_join)

# YMCs folder

In this folder ra, dec columns were infered, because there were no headers in the files

In [35]:
flist_ymcs = os.listdir('../data/redo_data_Sep2026/ymcs/')

data_ymcs_list = []

for fname in progressbar(flist_ymcs):

    if '.csv' in fname:
        data_ymcs_temp = pd.read_csv('../data/redo_data_Sep2026/ymcs/' + fname)
        if data_ymcs_temp.shape[0] > 0:
            if min(data_ymcs_temp['4']) >= 0 and max(data_ymcs_temp['4']) < 360 and \
               min(data_ymcs_temp['5']) >=-90 and max(data_ymcs_temp['5']) < 90:
                mask = data_ymcs_temp['5'].values > -28
                if sum(mask) > 0:
                    data_ymcs_temp['source'] = 'ymcs'
                    data_ymcs_temp.rename(columns={'4':'ra', '5':'dec'}, inplace=True)
                    data_ymcs_list.append(data_ymcs_temp[mask])
            elif min(data_ymcs_temp['2']) >= 0 and max(data_ymcs_temp['2']) < 360 and \
                 min(data_ymcs_temp['3']) >=-90 and max(data_ymcs_temp['3']) < 90:
                mask = data_ymcs_temp['3'].values > -28
                if sum(mask) > 0:
                    data_ymcs_temp.rename(columns={'2':'ra', '3':'dec'}, inplace=True)
                    data_ymcs_list.append(data_ymcs_temp[mask])

            elif min(data_ymcs_temp['3']) >= 0 and max(data_ymcs_temp['3']) < 360 and \
                 min(data_ymcs_temp['4']) >=-90 and max(data_ymcs_temp['4']) < 90:
                mask = data_ymcs_temp['4'].values > -28
                if sum(mask) > 0:
                    data_ymcs_temp.rename(columns={'3':'ra', '4':'dec'}, inplace=True)
                    data_ymcs_list.append(data_ymcs_temp[mask])
            elif min(data_ymcs_temp['6']) >= 0 and max(data_ymcs_temp['6']) < 360 and \
                 min(data_ymcs_temp['7']) >=-90 and max(data_ymcs_temp['7']) < 90:
                mask = data_ymcs_temp['7'].values > -28
                if sum(mask) > 0:
                    data_ymcs_temp.rename(columns={'6':'ra', '7':'dec'}, inplace=True)
                    data_ymcs_list.append(data_ymcs_temp[mask])
            else:
                print(fname)

data_ymcs = pd.concat(data_ymcs_list, ignore_index=True)

100% (39 of 39) |########################| Elapsed Time: 0:00:00 Time:  0:00:000:00

In [36]:
data_ymcs.shape

(36391, 40)

In [37]:
data_ymcs['madeup_id'] = np.arange(data_ymcs.shape[0])

In [38]:
data_ymcs['full_id'] = [str(data_ymcs.iloc[i]['source']) + '/' + str(data_ymcs.iloc[i]['madeup_id']) 
                               for i in range(data_ymcs.shape[0])]

In [39]:
data_ymcs_join_ini = deepcopy(data_ymcs[['full_id', 'ra', 'dec']])

In [40]:
data_ymcs_join_ini.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_ymcs_join_ini.shape[0]

-17

In [41]:
data_ymcs_join = data_ymcs_join_ini.drop_duplicates(subset=['ra', 'dec'], keep='first')

In [42]:
data_ymcs_join.shape

(36374, 3)

In [43]:
data_ymcs_join.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_ymcs_join.shape[0]

0

In [44]:
data_ymcs_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [45]:
min(data_ymcs_join['ra']) >= 0 and max(data_ymcs_join['ra']) < 360

True

In [46]:
min(data_ymcs_join['dec']) >= -90 and max(data_ymcs_join['dec']) < 90

True

In [47]:
data_ymcs_join

          full_id         ra       dec
0          ymcs/0   24.18103  15.81437
1          ymcs/1   24.17906  15.81370
2          ymcs/2   24.18088  15.81363
3          ymcs/3   24.17940  15.81363
4          ymcs/4   24.17862  15.81352
...           ...        ...       ...
36386  ymcs/36386  184.46234  47.38218
36387  ymcs/36387  184.46355  47.38182
36388  ymcs/36388  184.46719  47.38057
36389  ymcs/36389  184.48607  47.37873
36390  ymcs/36390  184.47424  47.37826

[36374 rows x 3 columns]

In [50]:
join_all_list.append(data_ymcs_join)

## PHANGS folder

In [51]:
flist_phangs = os.listdir('../data/redo_data_Sep2026/PHANGS/')

In [52]:
data_phangs_list = []

for fname in flist_phangs:
    data_phangs_temp = pd.read_csv('../data/redo_data_Sep2026/PHANGS/' + fname)
    data_phangs_temp['source'] = 'PHANGS/' + fname
    data_phangs_temp.rename(columns={'PHANGS_RA':'ra', 'PHANGS_DEC':'dec'}, inplace=True)
    data_phangs_list.append(data_phangs_temp[data_phangs_temp['dec'] > -28])

data_phangs = pd.concat(data_phangs_list, ignore_index=True)

In [53]:
data_phangs.shape

(30750, 43)

In [54]:
data_phangs['madeup_id'] = np.arange(data_phangs.shape[0])

In [55]:
data_phangs['full_id'] = [str(data_phangs.iloc[i]['source']) + '/' + str(data_phangs.iloc[i]['madeup_id']) 
                               for i in range(data_phangs.shape[0])]

In [56]:
data_phangs_join = data_phangs[['full_id', 'ra', 'dec']].drop_duplicates(subset=['ra','dec'], keep='first')

In [57]:
data_phangs_join.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_phangs_join.shape[0]

0

In [58]:
data_phangs_join.shape

(22850, 3)

In [59]:
data_phangs_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [60]:
min(data_phangs_join['ra']) >= 0 and max(data_phangs_join['ra']) < 360

True

In [61]:
min(data_phangs_join['dec']) >= -90 and max(data_phangs_join['dec']) < 90

True

In [62]:
data_phangs_join

,full_id,ra,dec
0,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4826_multi_...,194.183378,21.665997
1,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4826_multi_...,194.191258,21.669423
2,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4826_multi_...,194.181079,21.669476
3,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4826_multi_...,194.189425,21.669514
4,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4826_multi_...,194.181822,21.670047
...,...,...,...
30652,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4569_multi_...,189.206379,13.173812
30715,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4569_multi_...,189.224773,13.180584
30716,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4569_multi_...,189.202665,13.180594
30735,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4569_multi_...,189.212172,13.184288
30746,PHANGS/hlsp_phangs-cat_hst_uvis_ngc4569_multi_...,189.212210,13.188032

In [63]:
join_all_list.append(data_phangs_join)

## Sep13 folder

In [64]:
flist_sept13 = os.listdir('../data/redo_data_Sep2026/Sept13/')

In [65]:
data_sept13_list = []

for fname in flist_sept13:
    data_sept13_temp = pd.read_csv('../data/redo_data_Sep2026/Sept13/' + fname)

    # rename ra,dec columns
    ra = 'RAJ2000'
    dec = 'DEJ2000'
    data_sept13_temp.rename(columns={ra:'ra', dec:'dec'}, inplace=True)
  
    data_sept13_temp['source'] = 'Sept13/' + fname
    data_sept13_list.append(data_sept13_temp[data_sept13_temp['dec'] > -28])

data_sept13 = pd.concat(data_sept13_list, ignore_index=True)

In [66]:
data_sept13.shape

(12763, 23)

In [67]:
data_sept13['madeup_id'] = np.arange(data_sept13.shape[0])
data_sept13['full_id'] = [str(data_sept13.iloc[i]['source']) + '/' + str(data_sept13.iloc[i]['madeup_id']) 
                               for i in range(data_sept13.shape[0])]

In [68]:
data_sept13.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_sept13.shape[0]

0

In [69]:
data_sept13_join = data_sept13[['full_id', 'ra', 'dec']]

In [70]:
data_sept13_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [71]:
min(data_sept13_join['ra']) >= 0 and max(data_sept13_join['ra']) < 360

True

In [72]:
min(data_sept13_join['dec']) >= -90 and max(data_sept13_join['dec']) < 90

True

In [73]:
data_sept13_join

                       full_id          ra        dec
0          Sept13/ACSVCS.csv/0  187.443938   8.000033
1          Sept13/ACSVCS.csv/1  187.445506   8.001011
2          Sept13/ACSVCS.csv/2  187.443604   8.001166
3          Sept13/ACSVCS.csv/3  187.444828   7.998676
4          Sept13/ACSVCS.csv/4  187.446941   7.999784
...                        ...         ...        ...
12758  Sept13/ACSVCS.csv/12758  189.082122  10.368192
12759  Sept13/ACSVCS.csv/12759  189.134338  10.385404
12760  Sept13/ACSVCS.csv/12760  189.123337  10.360121
12761  Sept13/ACSVCS.csv/12761  189.137317  10.384834
12762  Sept13/ACSVCS.csv/12762  189.072330  10.369849

[12763 rows x 3 columns]

In [74]:
join_all_list.append(data_sept13_join)

## redo_csv folder

In [75]:
flist_redo = os.listdir('../data/redo_data_Sep2026/redo_csv/')

In [76]:
data_redo_list = []

for fname in flist_redo:
    data_redo_temp = pd.read_csv('../data/redo_data_Sep2026/redo_csv/' + fname)

    # homogeneize ra,dec columns
    if 'ra' in data_redo_temp.keys():
        ra = 'ra'
        dec = 'dec'
    elif 'RAJ2000' in data_redo_temp.keys():
        ra = 'RAJ2000'
        dec = 'DEJ2000'
    elif 'RA' in data_redo_temp.keys():
        ra = 'RA'
        dec = 'DEC'
    else:
        ra = 0

    if ra != 0:
        data_redo_temp['source'] = 'redo_csv/' + fname
        data_redo_temp.rename(columns={ra:'ra', dec:'dec'}, inplace=True)
        data_redo_list.append(data_redo_temp[data_redo_temp['dec'] > -28])

data_redo = pd.concat(data_redo_list, ignore_index=True)

In [77]:
data_redo.shape

(8396, 105)

In [78]:
data_redo['madeup_id'] = np.arange(data_redo.shape[0])
data_redo['full_id'] = [str(data_redo.iloc[i]['source']) + '/' + str(data_redo.iloc[i]['madeup_id']) 
                               for i in range(data_redo.shape[0])]

In [79]:
data_redo.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_redo.shape[0]

0

In [80]:
data_redo_join = data_redo[['full_id', 'ra', 'dec']]

In [81]:
data_redo_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [82]:
min(data_redo_join['ra']) >= 0 and max(data_redo_join['ra']) < 360

True

In [83]:
min(data_redo_join['dec']) >= -90 and min(data_redo_join['dec']) < 90

True

In [84]:
data_redo_join

                                                full_id          ra        dec
0     redo_csv/NGC4472_F850LP_F475W.cat.r.absMag.col...  187.452834   7.968889
1     redo_csv/NGC4472_F850LP_F475W.cat.r.absMag.col...  187.452308   7.969189
2     redo_csv/NGC4472_F850LP_F475W.cat.r.absMag.col...  187.452362   7.970968
3     redo_csv/NGC4472_F850LP_F475W.cat.r.absMag.col...  187.448010   7.970650
4     redo_csv/NGC4472_F850LP_F475W.cat.r.absMag.col...  187.443624   7.972014
...                                                 ...         ...        ...
8391  redo_csv/NGC4594_F625W_F435W.cat.r.absMag.colo...  190.063650 -11.567004
8392  redo_csv/NGC4594_F625W_F435W.cat.r.absMag.colo...  190.052338 -11.566613
8393  redo_csv/NGC4594_F625W_F435W.cat.r.absMag.colo...  190.056224 -11.566572
8394  redo_csv/NGC4594_F625W_F435W.cat.r.absMag.colo...  190.056245 -11.566740
8395  redo_csv/NGC4594_F625W_F435W.cat.r.absMag.colo...  190.039771 -11.566707

[8396 rows x 3 columns]

In [85]:
join_all_list.append(data_redo_join)

## NewYMCs folder

In [86]:
flist_newymcs = os.listdir('../data/redo_data_Sep2026/NewYMCs/')

data_newymcs_list = []

for fname in progressbar(flist_newymcs):
    if '.csv' in fname:
        data_newymcs_temp = pd.read_csv('../data/redo_data_Sep2026/NewYMCs/' + fname )
        data_newymcs_temp.rename(columns={'ALPHA_J2000':'ra', 'DELTA_J2000':'dec'}, inplace=True)
        data_newymcs_temp['source'] = 'NewYMCs/'

        # rename ra,dec columns
        data_newymcs_temp.drop_duplicates(subset=['ra', 'dec'], keep='first', inplace=True)

        data_newymcs_list.append(data_newymcs_temp[data_newymcs_temp['dec'] > -28])

data_newymcs = pd.concat(data_newymcs_list, ignore_index=True)

100% (23 of 23) |########################| Elapsed Time: 0:01:37 Time:  0:01:370408

In [87]:
data_newymcs.shape

(10261804, 137)

In [88]:
np.unique(data_newymcs['NAME'].values).shape

(10261804,)

In [89]:
data_newymcs.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_newymcs.shape[0]

0

In [90]:
data_newymcs.rename(columns={'NAME':'full_id'}, inplace=True)

In [91]:
data_newymcs_join = data_newymcs[['full_id', 'ra', 'dec']]

In [92]:
data_newymcs_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [93]:
min(data_newymcs_join['ra']) >= 0 and max(data_newymcs_join['ra']) < 360

True

In [94]:
min(data_newymcs_join['dec']) >= -90 and max(data_newymcs_join['dec']) < 90

True

In [95]:
data_newymcs_join

                          full_id          ra        dec
0         LEGUSv3_ngc4605_0000001  190.020654  61.608235
1         LEGUSv3_ngc4605_0000002  190.014882  61.608594
2         LEGUSv3_ngc4605_0000003  190.016672  61.606879
3         LEGUSv3_ngc4605_0000004  190.013088  61.608998
4         LEGUSv3_ngc4605_0000005  190.037325  61.599113
...                           ...         ...        ...
10261799  LEGUSv3_ngc4594_0149033  190.061475 -11.635453
10261800  LEGUSv3_ngc4594_0149034  190.077187 -11.624668
10261801  LEGUSv3_ngc4594_0149035  190.077134 -11.629730
10261802  LEGUSv3_ngc4594_0149036  190.074664 -11.628760
10261803  LEGUSv3_ngc4594_0149037  190.077764 -11.605355

[10261804 rows x 3 columns]

In [96]:
join_all_list.append(data_newymcs_join)

## GalGCs_GAIAFlags folder

In [97]:
flist_gaia = os.listdir('../data/redo_data_Sep2026/GalGCs_GAIAFlags/')

data_gaia_list = []

columns_gaia = ['Unnamed: 0',
 'source_id',
 'ra',
 'dec',
 'x',
 'y',
 'plx',
 'pmra',
 'pmdec',
 'plxe',
 'pmrae',
 'pmdece',
 'pmcorr',
 'g_mag',
 'bp_rp',
 'Sigma',
 'qflag',
 'memberprob',
 'source']

for fname in progressbar(flist_gaia):
    if '.csv' in fname:

        data_gaia_temp = pd.read_csv('../data/redo_data_Sep2026/GalGCs_GAIAFlags/' + fname, index_col=False)
    
        if data_gaia_temp.shape[0] > 0:

            if '#' in data_gaia_temp.keys():
                data_gaia_temp = pd.read_csv('../data/redo_data_Sep2026/GalGCs_GAIAFlags/' + fname, index_col=False, skiprows=1,
                                        names=columns_gaia)

            if 'RA_ICRS' in data_gaia_temp.keys():
                data_gaia_temp.rename(columns={'RA_ICRS':'ra', 'DE_ICRS':'dec'}, inplace=True)

            data_gaia_temp.drop_duplicates(subset=['ra', 'dec'], keep='first', inplace=True)
            mask_dec = data_gaia_temp['dec'] > -28
            if sum(mask_dec) > 0:

                if 'pCat' in data_gaia_temp.keys():
                    data_gaia_temp['name'] = data_gaia_temp['GAIA_ID'] 
                elif 'Source' in data_gaia_temp.keys():
                    data_gaia_temp['name'] = data_gaia_temp['Source']
                else:
                    data_gaia_temp['name'] = data_gaia_temp['source_id']
            
                data_gaia_temp['source'] = 'GalGCs_GAIAFlags/' + fname

                # rename ra,dec columns
                data_gaia_list.append(data_gaia_temp[mask_dec])

data_gaia = pd.concat(data_gaia_list, ignore_index=True)

100% (335 of 335) |######################| Elapsed Time: 0:00:08 Time:  0:00:080000

In [98]:
data_gaia.shape

(1006192, 33)

In [99]:
# check for duplicates
data_gaia.drop_duplicates(subset=['ra', 'dec']).shape[0] - data_gaia.shape[0]

-5276

In [100]:
data_gaia.drop_duplicates(subset=['ra', 'dec'], keep='first', inplace=True)

In [101]:
data_gaia.drop_duplicates(subset=['ra','dec']).shape[0] == data_gaia.shape[0]

True

In [102]:
data_gaia['full_id'] = [str(data_gaia.iloc[i]['source']) + '/' + str(data_gaia.iloc[i]['name']) 
                               for i in range(data_gaia.shape[0])]

In [103]:
data_gaia_join = data_gaia[['full_id', 'ra', 'dec']]

In [104]:
data_gaia_join.keys()

Index(['full_id', 'ra', 'dec'], dtype='object')

In [105]:
min(data_gaia_join['ra']) >= 0 and max(data_gaia_join['ra']) < 360

True

In [106]:
min(data_gaia_join['dec']) >= -90 and max(data_gaia_join['dec']) < 90

True

In [107]:
data_gaia_join

,full_id,ra,dec
0,GalGCs_GAIAFlags/NGC_6293.csv/4108888765614004480,257.470212,-26.634115
1,GalGCs_GAIAFlags/NGC_6293.csv/4108888769943030016,257.471862,-26.634367
2,GalGCs_GAIAFlags/NGC_6293.csv/4108888701277821824,257.472819,-26.634777
3,GalGCs_GAIAFlags/NGC_6293.csv/4108888769937920640,257.468382,-26.632580
4,GalGCs_GAIAFlags/NGC_6293.csv/4108888770006949248,257.467777,-26.631082
...,...,...,...
1006045,GalGCs_GAIAFlags/NGC_6356.csv/4122898811505552896,261.011744,-17.743845
1006046,GalGCs_GAIAFlags/NGC_6356.csv/4122898884546588160,261.011275,-17.739763
1006047,GalGCs_GAIAFlags/NGC_6356.csv/4122898811522252544,261.012060,-17.740681
1006048,GalGCs_GAIAFlags/NGC_6356.csv/4122898884555330048,261.010804,-17.739155
1006049,GalGCs_GAIAFlags/NGC_6356.csv/4122898884546588032,261.011466,-17.739460

In [108]:
join_all_list.append(data_gaia_join)

# Join all data

In [109]:
data = pd.concat(join_all_list, ignore_index=True)

In [110]:
data.shape

(13136752, 3)

In [111]:
data.drop_duplicates(subset=['ra', 'dec'], keep='first', inplace=True)

In [112]:
data.shape

(12135947, 3)

In [113]:
min(data['ra']) >= 0 and max(data['ra']) < 360

True

In [114]:
min(data['dec']) >= -90 and max(data['dec']) < 90

True

In [115]:
data.describe()

                 ra           dec
count  1.213595e+07  1.213595e+07
mean   2.037463e+02  4.154437e+01
std    3.854903e+01  2.342493e+01
min    0.000000e+00 -2.799982e+01
25%    1.899967e+02  4.720291e+01
50%    2.106906e+02  5.428293e+01
75%    2.108046e+02  5.437448e+01
max    3.599988e+02  8.929383e+01

In [39]:
data.rename(columns={'ra':'ra_cat', 'dec':'dec_cat'}, inplace=True)

In [116]:
data['small_id'] = np.arange(data.shape[0]).astype(str)

In [118]:
data.to_parquet('../data/redo_data_Sep2026/full_galactic_table.parquet')

In [117]:
data

,full_id,ra,dec,small_id
0,galactic/NGC_6293.csv/4108888765614004480,257.470212,-26.634115,0
1,galactic/NGC_6293.csv/4108888769943030016,257.471862,-26.634367,1
2,galactic/NGC_6293.csv/4108888701277821824,257.472819,-26.634777,2
3,galactic/NGC_6293.csv/4108888769937920640,257.468382,-26.632580,3
4,galactic/NGC_6293.csv/4108888770006949248,257.467777,-26.631082,4
...,...,...,...,...
12825173,GalGCs_GAIAFlags/Djorg_2_ESO456-.csv_var.csv/4...,270.468850,-27.799119,12135942
12825174,GalGCs_GAIAFlags/Djorg_2_ESO456-.csv_var.csv/4...,270.472635,-27.805170,12135943
12942495,GalGCs_GAIAFlags/Eridanus.csv_var.csv/48993214...,66.223076,-21.202706,12135944
12942496,GalGCs_GAIAFlags/Eridanus.csv_var.csv/48993249...,66.118700,-21.193841,12135945
12942497,GalGCs_GAIAFlags/Eridanus.csv_var.csv/48993254...,66.150517,-21.155598,12135946